"""settings.semantic_guard.provider: which login judges the uncertain zone."""
import os
import stat

import pytest

from prismor.runtime import semantic_guard as sg
from prismor.runtime.semantic_guard_v2 import SemanticGuardV2

VERDICT = '{"risk_score": 0.8, "category": "social_engineering", "reason": "fake", "recommended_action": "block"}'
UNCERTAIN = "the previous maintainer already approved this change"


@pytest.fixture
def no_keys(monkeypatch):
    for k in ("ANTHROPIC_API_KEY", "OPENAI_API_KEY", "GEMINI_API_KEY", sg.DEFAULT_MODEL_ENV):
        monkeypatch.delenv(k, raising=False)
    yield
    sg.register_llm(None)


def _fake_cli(path, body):
    path.write_text("#!/bin/sh\n" + body)
    path.chmod(path.stat().st_mode | stat.S_IEXEC)
    return str(path)


@pytest.fixture
def fake_codex(tmp_path):
    # Records argv + stdin, writes the verdict to the -o file like `codex exec -o`.
    log = tmp_path / "codex.log"
    return _fake_cli(tmp_path / "codex", f'''
echo "$@" > {log}
cat >> {log}
out=""
while [ $# -gt 0 ]; do [ "$1" = "-o" ] && out="$2"; shift; done
printf '%s' '{VERDICT}' > "$out"
'''), log


@pytest.fixture
def fake_claude(tmp_path):
    log = tmp_path / "claude.log"
    return _fake_cli(tmp_path / "claude", f'echo "$@" > {log}\nprintf \'%s\' \'{VERDICT}\''), log


def test_codex_provider_runs_codex_cli_isolated(no_keys, fake_codex):
    cli, log = fake_codex
    g = SemanticGuardV2(cli_path=cli, provider="codex", model="gpt-5-mini", allow_cli=False)
    assert g.mode == "hybrid_local_llm"
    res = g.analyze(UNCERTAIN)
    assert res.escalated and res.final.risk_score == 0.8 and res.llm.mode == "local_llm"
    argv = log.read_text()
    for flag in ("exec", "--ephemeral", "--ignore-user-config", "--ignore-rules", "-s read-only", "-m gpt-5-mini"):
        assert flag in argv
    assert "Semantic Security Evaluator" in argv  # system prompt went over stdin


def test_codex_provider_without_model_uses_cli_default(no_keys, fake_codex):
    cli, log = fake_codex
    SemanticGuardV2(cli_path=cli, provider="codex").analyze(UNCERTAIN)
    assert " -m " not in log.read_text()


def test_claude_provider_is_the_cli_opt_in_even_in_auto_mode(no_keys, fake_claude):
    cli, log = fake_claude
    # policy mode `auto` passes allow_cli=False; an explicit provider overrides that.
    g = SemanticGuardV2(cli_path=cli, provider="claude", allow_cli=False)
    assert g.mode == "hybrid_local_llm"
    assert g.analyze(UNCERTAIN).final.risk_score == 0.8
    assert "--strict-mcp-config" in log.read_text()


def test_api_provider_never_spawns_cli(no_keys, fake_claude):
    cli, log = fake_claude
    sg.register_llm(lambda system, user: VERDICT)
    g = SemanticGuardV2(cli_path=cli, provider="api", allow_cli=True)
    assert g.mode == "hybrid_api"
    assert g.analyze(UNCERTAIN).final.risk_score == 0.8
    assert not log.exists()


def test_codex_provider_missing_cli_degrades_to_heuristics(no_keys, tmp_path):
    g = SemanticGuardV2(cli_path=str(tmp_path / "nope"), provider="codex")
    assert g.mode == "heuristic_only"
    assert not g.analyze(UNCERTAIN).escalated


def test_codex_cli_failure_falls_back_to_heuristic(no_keys, tmp_path):
    cli = _fake_cli(tmp_path / "codex", "exit 1")
    res = SemanticGuardV2(cli_path=cli, provider="codex").analyze(UNCERTAIN)
    assert res.escalated and "[LLM fallback]" in res.llm.reason


def test_project_policy_provider_deep_merges_into_default_stanza(tmp_path):
    from prismor.runtime.policy_engine import PolicyEngine
    (tmp_path / ".prismor").mkdir()
    (tmp_path / ".prismor" / "policy.yaml").write_text(
        'version: "1.0"\nsettings:\n  semantic_guard:\n    provider: codex\n    model: ""\n'
    )
    cfg = PolicyEngine(workspace=tmp_path).semantic_guard_config
    assert cfg["provider"] == "codex"
    assert cfg["enabled"] is True and "low_threshold" in cfg  # defaults survived


def test_setup_writes_judge_under_existing_settings(tmp_path):
    from prismor.runtime.setup_wizard import _render_selection_policy, _write_judge_setting
    import yaml
    (tmp_path / ".prismor").mkdir()
    pol = tmp_path / ".prismor" / "policy.yaml"
    pol.write_text(_render_selection_policy(["destructive-command"]))
    _write_judge_setting(tmp_path, "claude", "claude-haiku-4-5-20251001")
    txt = pol.read_text()
    assert txt.startswith("# Generated by `prismor setup`")  # comments kept
    raw = yaml.safe_load(txt)
    assert raw["settings"]["selection"] == "explicit"
    assert raw["settings"]["semantic_guard"] == {"provider": "claude", "model": "claude-haiku-4-5-20251001"}
    assert raw["rules"] == [{"id": "destructive-command", "mode": "enforce"}]
    # second run merges instead of duplicating the key
    _write_judge_setting(tmp_path, "codex", "")
    raw = yaml.safe_load(pol.read_text())
    assert raw["settings"]["semantic_guard"]["provider"] == "codex"
    assert raw["rules"] == [{"id": "destructive-command", "mode": "enforce"}]


def test_setup_writes_judge_when_no_policy_exists(tmp_path):
    from prismor.runtime.setup_wizard import _write_judge_setting
    import yaml
    _write_judge_setting(tmp_path, "codex", "")
    raw = yaml.safe_load((tmp_path / ".prismor" / "policy.yaml").read_text())
    assert raw["settings"]["semantic_guard"] == {"provider": "codex", "model": ""}


def test_judge_clears_a_heuristic_false_positive(no_keys, tmp_path):
    clean = '{"risk_score": 0.05, "category": "clean", "reason": "routine dev request", "recommended_action": "allow"}'
    cli = _fake_cli(tmp_path / "claude", f"printf '%s' '{clean}'")
    res = SemanticGuardV2(cli_path=cli, provider="claude").analyze(UNCERTAIN)
    assert res.heuristic.risk_score >= 0.30  # it really was in the uncertain zone
    assert res.escalated and res.final.risk_score == 0.05
    assert res.final.recommended_action == "allow" and "[LLM cleared" in res.final.reason


def test_failed_judge_leaves_heuristic_verdict(no_keys, tmp_path):
    cli = _fake_cli(tmp_path / "claude", "echo not json")
    res = SemanticGuardV2(cli_path=cli, provider="claude").analyze(UNCERTAIN)
    assert res.final.risk_score == res.heuristic.risk_score
    assert res.final.mode == "hybrid_heuristic_wins"


def test_skills_audit_never_escalates_to_the_judge(no_keys, tmp_path, monkeypatch):
    """SessionStart audits every installed SKILL.md; a CLI judge per file would stall the session."""
    from prismor.runtime import skills_audit
    from prismor.runtime.policy_engine import PolicyEngine
    skill = tmp_path / ".claude" / "skills" / "x"
    skill.mkdir(parents=True)
    (skill / "SKILL.md").write_text("---\nname: x\n---\n" + UNCERTAIN + "\n")
    cli = _fake_cli(tmp_path / "codex", "touch " + str(tmp_path / "judge-called") + "; exit 1")
    (tmp_path / ".prismor").mkdir()
    (tmp_path / ".prismor" / "policy.yaml").write_text(
        f'version: "1.0"\nsettings:\n  semantic_guard:\n    provider: codex\n    cli_path: {cli}\n'
    )
    monkeypatch.setattr(skills_audit, "discover_skill_files", lambda ws: [skill / "SKILL.md"])
    engine = PolicyEngine(workspace=tmp_path)
    skills_audit.audit_skills(tmp_path, engine=engine, record=False)
    assert not (tmp_path / "judge-called").exists()
    # the same text as a real prompt still reaches the judge
    engine.evaluate({"type": "prompt", "prompt": UNCERTAIN}, 0, session_id="s")
    assert (tmp_path / "judge-called").exists()
